import { getPages } from "@/sanity/sanity-utils"
import "../globals.css"
import { Inter } from "next/font/google"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // get all of our pages
  const pages = await getPages()
  return (
    <html lang='en'>
      <body className='max-w-3xl mx-auto py-10'>
        <header className='flex items-start justify-between'>
          <div flex-1>
            <Link href='/' className='text-7xl font-extrbold'>
              Hello I&apos;m{" "}
              <span className='bg-gradient-to-r from-sky-300 via-blue-600 to-red-700 bg-clip-text flex-1 text-transparent'>
                {" "}
                Demian
              </span>
              !
            </Link>
            <p className='mt-5 text-2xl text-gray-600'>Check out my music!</p>
          </div>
          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className='bg-gray-100 rounded-lg text-gray-500 font-bold ml-5 px-4 whitespace-nowrap hover:bg-pink-500 hover:text-pink-100 transition'
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
